Pandas Concat function

It is used to combine series, dataframe and panel objects

In [2]:
import pandas as pd

In [3]:
sr1=pd.Series([0,1,2])
sr1

0    0
1    1
2    2
dtype: int64

In [7]:
sr2=pd.Series([3,4,5,6,7])
sr2

0    3
1    4
2    5
3    6
4    7
dtype: int64

 series, dataframe or panel objects whatever we use we need to give inputs in list in concat function. We can even concat two uneven series

In [8]:
pd.concat([sr1,sr2])

0    0
1    1
2    2
0    3
1    4
2    5
3    6
4    7
dtype: int64

In [10]:
df1=pd.DataFrame({"ID":[1,2,3,4],
                 "Name":["A","B","C","D"],
                 "Class":[5,6,7,8]})
df1

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [11]:
df2=pd.DataFrame({"ID":[5,6,7,8],
                 "Name":["E","F","G","H"],
                 "Class":[9,10,11,12]})
df2

   ID Name  Class
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12

In [15]:
pd.concat([df1,df2])

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12

In [16]:
pd.concat([df2,df1])

   ID Name  Class
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

If we need to see data column wise then we can provide 1 as axis value

In [17]:
pd.concat([df1,df2], axis=1)

   ID Name  Class  ID Name  Class
0   1    A      5   5    E      9
1   2    B      6   6    F     10
2   3    C      7   7    G     11
3   4    D      8   8    H     12

In [18]:
pd.concat([df1,df2], axis=0)

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12

To get the index number systematically we can use ignore_index

In [19]:
pd.concat([df1,df2], axis=0, ignore_index=True)

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8
4   5    E      9
5   6    F     10
6   7    G     11
7   8    H     12

In [20]:
df1=pd.DataFrame({"ID":[1,2,3,4],
                 "Name":["A","B","C","D"],
                 "Class":[5,6,7,8]})
df1

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [22]:
df2=pd.DataFrame({"ID":[7,8],
                 "Name":["G","H"],
                 "Class":[11,12]})
df2

   ID Name  Class
0   7    G     11
1   8    H     12

In [23]:
pd.concat([df1,df2])

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8
0   7    G     11
1   8    H     12

In [24]:
pd.concat([df1,df2],axis=1)

   ID Name  Class   ID Name  Class
0   1    A      5  7.0    G   11.0
1   2    B      6  8.0    H   12.0
2   3    C      7  NaN  NaN    NaN
3   4    D      8  NaN  NaN    NaN

If we use join ="inner" it will return only intersecting value rows

In [25]:
pd.concat([df1,df2],axis=1, join="inner")

   ID Name  Class  ID Name  Class
0   1    A      5   7    G     11
1   2    B      6   8    H     12

join="outer" will give output of all elements. It is union of both dataframe

In [26]:
pd.concat([df1,df2],axis=1, join="outer")

   ID Name  Class   ID Name  Class
0   1    A      5  7.0    G   11.0
1   2    B      6  8.0    H   12.0
2   3    C      7  NaN  NaN    NaN
3   4    D      8  NaN  NaN    NaN

When we use keys it provides labels to the dataframes which are merged

In [29]:
df1=pd.DataFrame({"ID":[1,2,3,4],
                 "Name":["A","B","C","D"],
                 "Class":[5,6,7,8]})
df1

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [36]:
df2=pd.DataFrame({"ID":[5,6,7,8],
                 "Name":["E","F","G","H"],
                 "Class":[9,10,11,12]})
df2

   ID Name  Class
0   5    E      9
1   6    F     10
2   7    G     11
3   8    H     12

In [37]:
pd.concat([df1,df2],keys=["df1","df2"])

       ID Name  Class
df1 0   1    A      5
    1   2    B      6
    2   3    C      7
    3   4    D      8
df2 0   5    E      9
    1   6    F     10
    2   7    G     11
    3   8    H     12

In [38]:
pd.concat([df1,df2],keys=["First df","Second df"])

             ID Name  Class
First df  0   1    A      5
          1   2    B      6
          2   3    C      7
          3   4    D      8
Second df 0   5    E      9
          1   6    F     10
          2   7    G     11
          3   8    H     12

In [39]:
pd.concat([df1,df2],axis=1,keys=["First df","Second df"])

  First df            Second df
        ID Name Class        ID Name Class
0        1    A     5         5    E     9
1        2    B     6         6    F    10
2        3    C     7         7    G    11
3        4    D     8         8    H    12

In [40]:
df1=pd.DataFrame({"ID":[1,2,3,4],
                 "Name":["A","B","C","D"],
                 "Class":[5,6,7,8]})
df1

   ID Name  Class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [41]:
df2=pd.DataFrame({"Marks":[40,63,91,34]})
df2

   Marks
0     40
1     63
2     91
3     34

In [42]:
pd.concat([df1,df2])

    ID Name  Class  Marks
0  1.0    A    5.0    NaN
1  2.0    B    6.0    NaN
2  3.0    C    7.0    NaN
3  4.0    D    8.0    NaN
0  NaN  NaN    NaN   40.0
1  NaN  NaN    NaN   63.0
2  NaN  NaN    NaN   91.0
3  NaN  NaN    NaN   34.0