Pandas GroupBy function

Pandas groupby function is used to split into groups based on some criteria

In [5]:
import pandas as pd

In [6]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Student_results2.csv")
df

   Student ID Section  Class  Study hrs  Social Media  percentage
0        1001       A     10          2             3          50
1        1002       B     10          6             2          80
2        1003       A     10          3             2          60
3        1004       C     11          0             1          45
4        1005       C     12          5             2          75

We can use this to split a column and store it in another variable

In [7]:
gr1=df.groupby(by="Section")
gr1

Multiple values are taken of column (section) and merged into single group and index values are displayed

In [8]:
gr1.groups

{'A': [0, 2], 'B': [1], 'C': [3, 4]}

WE can group multiple columns as well

In [9]:
df.groupby(["Section","Class"]).groups

{('A', 10): [0, 2], ('B', 10): [1], ('C', 11): [3], ('C', 12): [4]}

It shows the keys and values present in dataframe where section is the key and df_1 is value

In [10]:
for Section, df_1 in gr1:
    print(Section)
    print(df_1)

A
   Student ID Section  Class  Study hrs  Social Media  percentage
0        1001       A     10          2             3          50
2        1003       A     10          3             2          60
B
   Student ID Section  Class  Study hrs  Social Media  percentage
1        1002       B     10          6             2          80
C
   Student ID Section  Class  Study hrs  Social Media  percentage
3        1004       C     11          0             1          45
4        1005       C     12          5             2          75

In [11]:
list(gr1)

[('A',
     Student ID Section  Class  Study hrs  Social Media  percentage
  0        1001       A     10          2             3          50
  2        1003       A     10          3             2          60),
 ('B',
     Student ID Section  Class  Study hrs  Social Media  percentage
  1        1002       B     10          6             2          80),
 ('C',
     Student ID Section  Class  Study hrs  Social Media  percentage
  3        1004       C     11          0             1          45
  4        1005       C     12          5             2          75)]

In [13]:
dict(list(gr1))

{'A':    Student ID Section  Class  Study hrs  Social Media  percentage
 0        1001       A     10          2             3          50
 2        1003       A     10          3             2          60,
 'B':    Student ID Section  Class  Study hrs  Social Media  percentage
 1        1002       B     10          6             2          80,
 'C':    Student ID Section  Class  Study hrs  Social Media  percentage
 3        1004       C     11          0             1          45
 4        1005       C     12          5             2          75}

In [16]:
gr3=df.groupby("Class").get_group(10)
gr3

   Student ID Section  Class  Study hrs  Social Media  percentage
0        1001       A     10          2             3          50
1        1002       B     10          6             2          80
2        1003       A     10          3             2          60

In [20]:
gr3=df.groupby("Section").get_group("A")
gr3

   Student ID Section  Class  Study hrs  Social Media  percentage
0        1001       A     10          2             3          50
2        1003       A     10          3             2          60

If we use sum we can add the values

In [21]:
gr1.sum()

         Student ID  Class  Study hrs  Social Media  percentage
Section
A              2004     20          5             5         110
B              1002     10          6             2          80
C              2009     23          5             3         120

In [22]:
gr1.mean()

         Student ID  Class  Study hrs  Social Media  percentage
Section
A            1002.0   10.0        2.5           2.5        55.0
B            1002.0   10.0        6.0           2.0        80.0
C            1004.5   11.5        2.5           1.5        60.0

In [23]:
gr1.describe()

        Student ID                                                      \
             count    mean       std     min      25%     50%      75%
Section
A              2.0  1002.0  1.414214  1001.0  1001.50  1002.0  1002.50
B              1.0  1002.0       NaN  1002.0  1002.00  1002.0  1002.00
C              2.0  1004.5  0.707107  1004.0  1004.25  1004.5  1004.75

                Class        ... Social Media      percentage        \
            max count  mean  ...          75%  max      count  mean
Section                      ...
A        1003.0   2.0  10.0  ...         2.75  3.0        2.0  55.0
B        1002.0   1.0  10.0  ...         2.00  2.0        1.0  80.0
C        1005.0   2.0  11.5  ...         1.75  2.0        2.0  60.0


               std   min   25%   50%   75%   max
Section
A         7.071068  50.0  52.5  55.0  57.5  60.0
B              NaN  80.0  80.0  80.0  80.0  80.0
C        21.213203  45.0  52.5  60.0  67.5  75.0

[3 rows x 40 columns]

Using aggregate function we can have multiple types of function

In [24]:
gr1.agg(["sum","max","mean"])

        Student ID               Class           Study hrs           \
               sum   max    mean   sum max  mean       sum max mean
Section
A             2004  1003  1002.0    20  10  10.0         5   3  2.5
B             1002  1002  1002.0    10  10  10.0         6   6  6.0
C             2009  1005  1004.5    23  12  11.5         5   5  2.5

        Social Media          percentage
                 sum max mean        sum max  mean
Section
A                  5   3  2.5        110  60  55.0
B                  2   2  2.0         80  80  80.0
C                  3   2  1.5        120  75  60.0