Pandas Datetimeindex functionality

we can change date column from string to DateTime

In [29]:
import pandas as pd

In [30]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\VC_Startups_3.csv")
df

         Date  R&D Spend  Marketing Spend  Profit
0  01-07-2019     165349           136897  192261
1  02-07-2019     133848           151377  191792
2  03-07-2019     153441           327468  191050
3  04-07-2019     144372            63338  182901
4  05-07-2019     142107            91391  166187
5  08-07-2019     131876            99814  156991
6  09-07-2019     134615           147198  156122
7  10-07-2019     130298           145530  155752
8  11-07-2019     120542           148718  152211
9  12-07-2019     123334           108679  149759

In [31]:
df.dtypes

Date               object
R&D Spend           int64
Marketing Spend     int64
Profit              int64
dtype: object

In [32]:
type(df.Date[0])

str

If we want to change datatype of date from string to datetime then we can use parsedates

In [33]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\VC_Startups_3.csv", parse_dates=["Date"])
df

        Date  R&D Spend  Marketing Spend  Profit
0 2019-01-07     165349           136897  192261
1 2019-02-07     133848           151377  191792
2 2019-03-07     153441           327468  191050
3 2019-04-07     144372            63338  182901
4 2019-05-07     142107            91391  166187
5 2019-08-07     131876            99814  156991
6 2019-09-07     134615           147198  156122
7 2019-10-07     130298           145530  155752
8 2019-11-07     120542           148718  152211
9 2019-12-07     123334           108679  149759

In [34]:
df.dtypes

Date               datetime64[ns]
R&D Spend                   int64
Marketing Spend             int64
Profit                      int64
dtype: object

In [35]:
type(df.Date[0])

pandas._libs.tslibs.timestamps.Timestamp