Pandas FillNA

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv")
df

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN

We can fill missing values with help of fill na by providing values in its parameters

In [3]:
df.fillna(1)

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",1,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",1,3138627.0,8%
11,12,1,1,1,2024,1,1,1.0,1

In [4]:
df.fillna({"Name":"none","Industry":"nothing"})

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,none,nothing,2024,NaN,NaN,NaN,NaN

Method is use when we need to fill the values which are present in forward or backward index

In [6]:
df.fillna(method="ffill")

C:\Users\shwet\AppData\Local\Temp\ipykernel_11116\3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990","5,635,276 Dollars",3138627.0,8%
11,12,Yes,Techdrill,Health,2024,"$10,573,990","5,635,276 Dollars",3138627.0,8%

In [8]:
df.ffill()

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990","5,635,276 Dollars",3138627.0,8%
11,12,Yes,Techdrill,Health,2024,"$10,573,990","5,635,276 Dollars",3138627.0,8%

In [9]:
df.bfill()

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180","5,635,276 Dollars",11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN

It fills the values in next rows from values present in previous rows

In [17]:
df.ffill(axis=0)

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990","5,635,276 Dollars",3138627.0,8%
11,12,Yes,Techdrill,Health,2024,"$10,573,990","5,635,276 Dollars",3138627.0,12%

It fills the values in previous columns from values present on next column

In [16]:
df.bfill(axis=1)

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",11901180.0,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",3138627.0,3138627.0,8%
11,12,2024,2024,2024,2024,12%,12%,12%,12%

In [15]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv")
df

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,12%

If method is specified, this is the maximum number of consecutive  NaN values to forward/backward fill.

In [25]:
df.fillna("jj", limit=1)

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",jj,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,jj,jj,jj,2024,jj,NaN,jj,12%

In [26]:
df.fillna("jj", limit=2)

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",jj,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",jj,3138627.0,8%
11,12,jj,jj,jj,2024,jj,NaN,jj,12%

In [28]:
df.fillna(method="ffill", limit=1)

C:\Users\shwet\AppData\Local\Temp\ipykernel_11116\2400329422.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", limit=1)

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180","3,878,113 Dollars",11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990","5,635,276 Dollars",3138627.0,8%
11,12,Yes,Techdrill,Health,2024,"$10,573,990",NaN,3138627.0,12%

In [29]:
df.fillna(5,inplace=True)

In [30]:
df

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",5,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",5,3138627.0,8%
11,12,5,5,5,2024,5,5,5.0,12%