Pandas replace()

In [48]:
import pandas as pd

In [49]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv")
df

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",0.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",0.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",0.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",0.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,12%

It replaces the existing value with the value we provide

In [50]:
df.replace(to_replace="Health", value="Finance")

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Finance,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",0.0,26%
4,5,Yes,Techdrill,Finance,2009,"$10,573,990","7,435,363 Dollars",0.0,8%
5,6,Yes,Techline,Finance,2006,"$13,898,119","5,470,303 Dollars",0.0,23%
6,7,No,Cityace,Finance,2010,"$9,254,614","6,249,498 Dollars",0.0,6%
7,8,Yes,Kayelectronics,Finance,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Finance,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,12%

We can directly replace words without using "to_replace,value"

In [51]:
df.replace("Health","Finance")

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Finance,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",0.0,26%
4,5,Yes,Techdrill,Finance,2009,"$10,573,990","7,435,363 Dollars",0.0,8%
5,6,Yes,Techline,Finance,2006,"$13,898,119","5,470,303 Dollars",0.0,23%
6,7,No,Cityace,Finance,2010,"$9,254,614","6,249,498 Dollars",0.0,6%
7,8,Yes,Kayelectronics,Finance,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Finance,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,12%

In [52]:
df.replace(12,15)

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",0.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",0.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",0.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",0.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,15,NaN,NaN,NaN,2024,NaN,NaN,NaN,12%

Can replace all values with one single value at a time

In [53]:
df.replace([0,1,2,3,4,5,6,7,8,9,10,11],0)

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,0,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,0,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,0,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,0,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",0.0,26%
4,0,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",0.0,8%
5,0,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",0.0,23%
6,0,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",0.0,6%
7,0,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,0,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,0,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,0,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,12%

In [54]:
df.replace([0,1,2,3,4,5,6,7,8,9,10,11],[21,22,23,24,25,26,27,28,29,30,31,32])

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,22,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,23,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,24,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,25,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",21.0,26%
4,26,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",21.0,8%
5,27,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",21.0,23%
6,28,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",21.0,6%
7,29,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,30,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,31,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,32,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,12%

In [55]:
df.replace({"Industry": "Health"},"Finance")

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Finance,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",0.0,26%
4,5,Yes,Techdrill,Finance,2009,"$10,573,990","7,435,363 Dollars",0.0,8%
5,6,Yes,Techline,Finance,2006,"$13,898,119","5,470,303 Dollars",0.0,23%
6,7,No,Cityace,Finance,2010,"$9,254,614","6,249,498 Dollars",0.0,6%
7,8,Yes,Kayelectronics,Finance,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Finance,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,12%

In [56]:
df.replace({"Profit":6597557.0},1)

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",0.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",0.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",0.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",0.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,12%

It will not work as it needs regex to change string starting from a-z to the provided value

In [57]:
df.replace("[A-Za-z]",0)

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",0.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",0.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",0.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",0.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,12%

In [58]:
df.replace("[A-Za-z]",0, regex=True)

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,0.0,0.0,0.0,2009,"$11,757,018",0.0,5274553.0,30%
1,2,0.0,0.0,0.0,2010,"$12,329,371",0.0,11412916.0,20%
2,3,0.0,0.0,0.0,2012,"$10,597,009",0.0,3005820.0,7%
3,4,0.0,0.0,0.0,2013,"$14,026,934",0.0,0.0,26%
4,5,0.0,0.0,0.0,2009,"$10,573,990",0.0,0.0,8%
5,6,0.0,0.0,0.0,2006,"$13,898,119",0.0,0.0,23%
6,7,0.0,0.0,0.0,2010,"$9,254,614",0.0,0.0,6%
7,8,0.0,0.0,0.0,2009,"$9,451,943",0.0,5573830.0,4%
8,9,0.0,0.0,0.0,2011,"$14,001,180",NaN,11901180.0,18%
9,10,0.0,0.0,0.0,2011,"$11,088,336",0.0,5453060.0,7%
10,11,0.0,0.0,0.0,0,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,12%

For changing values of any specific column

In [59]:
df.replace({"Industry":"[A-Za-z]"},0, regex=True)

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,0.0,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,0.0,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,0.0,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,0.0,2013,"$14,026,934","7,429,377 Dollars",0.0,26%
4,5,Yes,Techdrill,0.0,2009,"$10,573,990","7,435,363 Dollars",0.0,8%
5,6,Yes,Techline,0.0,2006,"$13,898,119","5,470,303 Dollars",0.0,23%
6,7,No,Cityace,0.0,2010,"$9,254,614","6,249,498 Dollars",0.0,6%
7,8,Yes,Kayelectronics,0.0,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,0.0,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,0.0,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,0.0,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,12%

Method is used when we need to replace values with previous values

In [60]:
df.replace("Health", method="ffill")

C:\Users\shwet\AppData\Local\Temp\ipykernel_21692\3516129170.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace("Health", method="ffill")

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Financial Services,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",0.0,26%
4,5,Yes,Techdrill,IT Services,2009,"$10,573,990","7,435,363 Dollars",0.0,8%
5,6,Yes,Techline,IT Services,2006,"$13,898,119","5,470,303 Dollars",0.0,23%
6,7,No,Cityace,IT Services,2010,"$9,254,614","6,249,498 Dollars",0.0,6%
7,8,Yes,Kayelectronics,IT Services,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Government Services,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,12%

In [61]:
df.replace("Health", method="bfill")

C:\Users\shwet\AppData\Local\Temp\ipykernel_21692\2356863291.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace("Health", method="bfill")

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,IT Services,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",0.0,26%
4,5,Yes,Techdrill,IT Services,2009,"$10,573,990","7,435,363 Dollars",0.0,8%
5,6,Yes,Techline,IT Services,2006,"$13,898,119","5,470,303 Dollars",0.0,23%
6,7,No,Cityace,IT Services,2010,"$9,254,614","6,249,498 Dollars",0.0,6%
7,8,Yes,Kayelectronics,IT Services,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,NaN,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,12%

In [62]:
df.replace(0,method="bfill", limit=1)

C:\Users\shwet\AppData\Local\Temp\ipykernel_21692\141041420.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace(0,method="bfill", limit=1)

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",0.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",0.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",0.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",5573830.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,12%

In [63]:
df.replace(0,method="bfill",limit=2)

C:\Users\shwet\AppData\Local\Temp\ipykernel_21692\2021079640.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace(0,method="bfill",limit=2)

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",0.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",0.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",5573830.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",5573830.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,12%

In [65]:
df.replace(0,100, inplace=True)
df

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",100.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",100.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",100.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",100.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,12%

Now since we used inplace so it modified the original dataframe so now when we call the original dataframe it shows updated values

In [66]:
df

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",100.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",100.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",100.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",100.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,12%