Pandas Merge Function

Pandas merge function connects columns or indexes in dataframe based on one or more keys.

In [2]:
import pandas as pd

In [3]:
df1=pd.DataFrame({"ID":[1,2,3,4],
                "Class":[9,10,11,12]})
df1

   ID  Class
0   1      9
1   2     10
2   3     11
3   4     12

In [8]:
df2=pd.DataFrame({"ID":[1,2,3,5],
                "Name":["A","B","C","D"]})
df2

   ID Name
0   1    A
1   2    B
2   3    C
3   5    D

For merging two columns we need to use pd.merge() in which "on" is a parameter where we can use label for single key and list for multiple keys

In [9]:
pd.merge(df1,df2,on="ID")

   ID  Class Name
0   1      9    A
1   2     10    B
2   3     11    C

In [10]:
pd.merge(df2,df1,on="ID")

   ID Name  Class
0   1    A      9
1   2    B     10
2   3    C     11

Here only 3 rows are printed bcaz only 3 rows are similar

In [11]:
pd.merge(df1,df2,on="ID")

   ID  Class Name
0   1      9    A
1   2     10    B
2   3     11    C

In [13]:
pd.merge(df1,df2,on="ID", how="inner")

   ID  Class Name
0   1      9    A
1   2     10    B
2   3     11    C

It will take according to first dataframe since ID=5 is not there in df1 so NaN is printed is name

In [14]:
pd.merge(df1,df2,on="ID", how="left")

   ID  Class Name
0   1      9    A
1   2     10    B
2   3     11    C
3   4     12  NaN

In [15]:
pd.merge(df1,df2,on="ID", how="right")

   ID  Class Name
0   1    9.0    A
1   2   10.0    B
2   3   11.0    C
3   5    NaN    D

If we want to print all values we need to take how=outer

In [16]:
pd.merge(df1,df2,on="ID", how="outer")

   ID  Class Name
0   1    9.0    A
1   2   10.0    B
2   3   11.0    C
3   4   12.0  NaN
4   5    NaN    D

If we want to know which values belongs to which class then we need to use indicator=True

In [18]:
pd.merge(df1,df2,on="ID", how="outer", indicator=True)

   ID  Class Name      _merge
0   1    9.0    A        both
1   2   10.0    B        both
2   3   11.0    C        both
3   4   12.0  NaN   left_only
4   5    NaN    D  right_only

In [19]:
df1

   ID  Class
0   1      9
1   2     10
2   3     11
3   4     12

In [20]:
df2

   ID Name
0   1    A
1   2    B
2   3    C
3   5    D

In [21]:
df2=pd.DataFrame({"ID":[5,6,7,8],
                "Name":["A","B","C","D"]})
df2

   ID Name
0   5    A
1   6    B
2   7    C
3   8    D

If we want to show both index then use this. Usually used when we have multiple index to show

In [22]:
pd.merge(df1,df2,left_index=True,right_index=True)

   ID_x  Class  ID_y Name
0     1      9     5    A
1     2     10     6    B
2     3     11     7    C
3     4     12     8    D

In [25]:
pd.merge(df1,df2)

Empty DataFrame
Columns: [ID, Class, Name]
Index: []

Now we will check what if we have both dataframe with same class data

In [26]:
df1=pd.DataFrame({"ID":[1,2,3,4],
                "Class":[9,10,11,12]})
df1

   ID  Class
0   1      9
1   2     10
2   3     11
3   4     12

In [27]:
df2=pd.DataFrame({"ID":[1,2,3,4],
                "Class":[9,10,11,12]})
df2

   ID  Class
0   1      9
1   2     10
2   3     11
3   4     12

In [28]:
pd.merge(df1,df2,on="ID")

   ID  Class_x  Class_y
0   1        9        9
1   2       10       10
2   3       11       11
3   4       12       12

We can use suffixes for overlapping columns and can provide our names but need to provide values in tuple form

In [31]:
pd.merge(df1,df2,on="ID", suffixes=("_Higher","_Middle"))

   ID  Class_Higher  Class_Middle
0   1             9             9
1   2            10            10
2   3            11            11
3   4            12            12