Pandas loc

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Student_results1.csv")
df

   Student ID  Class  Study hrs  Social Media  percentage
0        1001     10          2             3          50
1        1002     10          6             2          80
2        1003     10          3             2          60
3        1004     11          0             1          45
4        1005     12          5             2          75

It will return the values present in the rows

In [3]:
df.loc[0]

Student ID      1001
Class             10
Study hrs          2
Social Media       3
percentage        50
Name: 0, dtype: int64

In [7]:
df.loc[4]

Student ID      1005
Class             12
Study hrs          5
Social Media       2
percentage        75
Name: 4, dtype: int64

For multiple rows

In [9]:
df.loc[[0,4]]

   Student ID  Class  Study hrs  Social Media  percentage
0        1001     10          2             3          50
4        1005     12          5             2          75

We can access specific value present in a column by using df.loc[index,column]

In [11]:
df.loc[4,"Class"]

12

by using slicing method

In [15]:
df.loc[0:3,"Class"]

0    10
1    10
2    10
3    11
Name: Class, dtype: int64

In [21]:
df.loc[0:4,"percentage"]

0    50
1    80
2    60
3    45
4    75
Name: percentage, dtype: int64

It is used to display which rows we want to print and which we dont. Need to provide exact no of booleean values for the rows present in dataset eg: df.loc[[boolean values]]

In [29]:
df.loc[[True, False, True, False,True]]

   Student ID  Class  Study hrs  Social Media  percentage
0        1001     10          2             3          50
2        1003     10          3             2          60
4        1005     12          5             2          75

It will print values less than 11 present in class column eg:df.loc[df[column] < value]

In [33]:
df.loc[df["Class"]<11]

   Student ID  Class  Study hrs  Social Media  percentage
0        1001     10          2             3          50
1        1002     10          6             2          80
2        1003     10          3             2          60

It will only print percentage values less than 11 as per class column

In [38]:
df.loc[df["Class"]<11,"percentage"]

0    50
1    80
2    60
Name: percentage, dtype: int64

Pandas iloc

In [40]:
df.iloc[0]

Student ID      1001
Class             10
Study hrs          2
Social Media       3
percentage        50
Name: 0, dtype: int64

If we use double brackets it will print specific row

In [41]:
df.iloc[[0]]

   Student ID  Class  Study hrs  Social Media  percentage
0        1001     10          2             3          50

Will only print values present in first column

In [42]:
df.iloc[:,0]

0    1001
1    1002
2    1003
3    1004
4    1005
Name: Student ID, dtype: int64

In [43]:
df.iloc[:,3]

0    3
1    2
2    2
3    1
4    2
Name: Social Media, dtype: int64

It will show error as we cannot do label indexing in this

In [44]:
df.loc[:,0]

KeyError: 0

It will print values of mentioned rows

In [48]:
df.iloc[[0,1]]

   Student ID  Class  Study hrs  Social Media  percentage
0        1001     10          2             3          50
1        1002     10          6             2          80

It will print specific value present in index and column eg: df.loc[index,column]

In [50]:
df.iloc[0,1]

10

In [56]:
df.loc[[False,True,False,True,False]]

   Student ID  Class  Study hrs  Social Media  percentage
1        1002     10          6             2          80
3        1004     11          0             1          45