Pandas Melt function

Pandas Melt function is used to transform or reshape the data

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Movie_ratings.csv")
df

       Genre  Year  Budget(M$)  Ratings%
0     Action  2008          28        48
1     Action  2009         200        63
2     Action  2008          32        57
3     Action  2010          20        52
4  Adventure  2009          18        84
5  Adventure  2010         105        44
6     Comedy  2010          20        70
7     Comedy  2008           8        81
8     Comedy  2009          30        71

In [3]:
pd.melt(df)

      variable      value
0        Genre     Action
1        Genre     Action
2        Genre     Action
3        Genre     Action
4        Genre  Adventure
5        Genre  Adventure
6        Genre     Comedy
7        Genre     Comedy
8        Genre     Comedy
9         Year       2008
10        Year       2009
11        Year       2008
12        Year       2010
13        Year       2009
14        Year       2010
15        Year       2010
16        Year       2008
17        Year       2009
18  Budget(M$)         28
19  Budget(M$)        200
20  Budget(M$)         32
21  Budget(M$)         20
22  Budget(M$)         18
23  Budget(M$)        105
24  Budget(M$)         20
25  Budget(M$)          8
26  Budget(M$)         30
27    Ratings%         48
28    Ratings%         63
29    Ratings%         57
30    Ratings%         52
31    Ratings%         84
32    Ratings%         44
33    Ratings%         70
34    Ratings%         81
35    Ratings%         71

If we need a extra column we can use identifies

In [4]:
pd.melt(df,id_vars=["Genre"])

        Genre    variable  value
0      Action        Year   2008
1      Action        Year   2009
2      Action        Year   2008
3      Action        Year   2010
4   Adventure        Year   2009
5   Adventure        Year   2010
6      Comedy        Year   2010
7      Comedy        Year   2008
8      Comedy        Year   2009
9      Action  Budget(M$)     28
10     Action  Budget(M$)    200
11     Action  Budget(M$)     32
12     Action  Budget(M$)     20
13  Adventure  Budget(M$)     18
14  Adventure  Budget(M$)    105
15     Comedy  Budget(M$)     20
16     Comedy  Budget(M$)      8
17     Comedy  Budget(M$)     30
18     Action    Ratings%     48
19     Action    Ratings%     63
20     Action    Ratings%     57
21     Action    Ratings%     52
22  Adventure    Ratings%     84
23  Adventure    Ratings%     44
24     Comedy    Ratings%     70
25     Comedy    Ratings%     81
26     Comedy    Ratings%     71

In [5]:
pd.melt(df,id_vars=["Year"])

    Year    variable      value
0   2008       Genre     Action
1   2009       Genre     Action
2   2008       Genre     Action
3   2010       Genre     Action
4   2009       Genre  Adventure
5   2010       Genre  Adventure
6   2010       Genre     Comedy
7   2008       Genre     Comedy
8   2009       Genre     Comedy
9   2008  Budget(M$)         28
10  2009  Budget(M$)        200
11  2008  Budget(M$)         32
12  2010  Budget(M$)         20
13  2009  Budget(M$)         18
14  2010  Budget(M$)        105
15  2010  Budget(M$)         20
16  2008  Budget(M$)          8
17  2009  Budget(M$)         30
18  2008    Ratings%         48
19  2009    Ratings%         63
20  2008    Ratings%         57
21  2010    Ratings%         52
22  2009    Ratings%         84
23  2010    Ratings%         44
24  2010    Ratings%         70
25  2008    Ratings%         81
26  2009    Ratings%         71

Unpivot

A dataframe turn it from a wide format(many columns) to a long format(few columns but many rows)

if we want to see values according to specific column then we can use value_vars

In [6]:
pd.melt(df,id_vars=["Year"], value_vars=["Genre"])

   Year variable      value
0  2008    Genre     Action
1  2009    Genre     Action
2  2008    Genre     Action
3  2010    Genre     Action
4  2009    Genre  Adventure
5  2010    Genre  Adventure
6  2010    Genre     Comedy
7  2008    Genre     Comedy
8  2009    Genre     Comedy

In [8]:
pd.melt(df,id_vars=["Year"], value_vars=["Ratings%"])

   Year  variable  value
0  2008  Ratings%     48
1  2009  Ratings%     63
2  2008  Ratings%     57
3  2010  Ratings%     52
4  2009  Ratings%     84
5  2010  Ratings%     44
6  2010  Ratings%     70
7  2008  Ratings%     81
8  2009  Ratings%     71

Variable name is given by default but if we want to give different name then we can use var_name

In [10]:
pd.melt(df,id_vars=["Year"], value_vars=["Ratings%"], var_name="Category")

   Year  Category  value
0  2008  Ratings%     48
1  2009  Ratings%     63
2  2008  Ratings%     57
3  2010  Ratings%     52
4  2009  Ratings%     84
5  2010  Ratings%     44
6  2010  Ratings%     70
7  2008  Ratings%     81
8  2009  Ratings%     71

similarly we can change for value

In [11]:
pd.melt(df,id_vars=["Year"], value_vars=["Ratings%"], var_name="Category", value_name="Data")

   Year  Category  Data
0  2008  Ratings%    48
1  2009  Ratings%    63
2  2008  Ratings%    57
3  2010  Ratings%    52
4  2009  Ratings%    84
5  2010  Ratings%    44
6  2010  Ratings%    70
7  2008  Ratings%    81
8  2009  Ratings%    71