How to create python pandas DataFrame

In [1]:
import pandas as pd

In [3]:
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [7]:
li=['a','b','c','d']
print(li)

['a', 'b', 'c', 'd']

In [8]:
df=pd.DataFrame(li)
print(df)

   0
0  a
1  b
2  c
3  d

In [9]:
df

   0
0  a
1  b
2  c
3  d

In [10]:
ml=[[1,2,3],[4,5,6],[7,8,9]]
print(ml)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
df1=pd.DataFrame(ml)

In [12]:
df1

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [21]:
dict_1={"ID":[1,2,3,4]}
print(dict_1)

{'ID': [1, 2, 3, 4]}

In [22]:
df2=pd.DataFrame(dict_1)

In [23]:
df2

   ID
0   1
1   2
2   3
3   4

In [24]:
dict_1={"ID":[1,2,3,4],"SN":[5,6,7,8]}
print(dict_1)

{'ID': [1, 2, 3, 4], 'SN': [5, 6, 7, 8]}

In [30]:
df=pd.DataFrame(dict_1)
df

   ID  SN
0   1   5
1   2   6
2   3   7
3   4   8

In [31]:
df2

   ID
0   1
1   2
2   3
3   4

In [35]:
ld=[{"a":1,"b":2},{"a":3,"b":4}]
ld

[{'a': 1, 'b': 2}, {'a': 3, 'b': 4}]

In [37]:
df4=pd.DataFrame(ld)
df4

   a  b
0  1  2
1  3  4

In [42]:
dsr={"ID":pd.Series([1,2,3]),"SN":pd.Series([111,222,333])}
dsr

{'ID': 0    1
 1    2
 2    3
 dtype: int64,
 'SN': 0    111
 1    222
 2    333
 dtype: int64}

In [43]:
df5=pd.DataFrame(dsr)
df5

   ID   SN
0   1  111
1   2  222
2   3  333