Pandas interpolate()

In [10]:
import pandas as pd

In [11]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Student_11.csv")
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2019      1001.0     10        2.0        50.0
1  02-07-2019      1002.0     10        NaN        80.0
2  03-07-2019         NaN     10        3.0        60.0
3  06-07-2019         NaN     11        0.0         NaN
4  07-07-2019      1005.0     11        4.0         NaN
5  08-07-2019         NaN     11       10.0         NaN
6  09-07-2019      1007.0     12        4.0        80.0
7  10-07-2019      1008.0     12        NaN        90.0
8  11-07-2019      1009.0     12        NaN        60.0
9  12-07-2019      1010.0     12        6.0        85.0

When we use interploate function it guesses the missing values

In [12]:
df.interpolate()

C:\Users\shwet\AppData\Local\Temp\ipykernel_28348\4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2019      1001.0     10   2.000000        50.0
1  02-07-2019      1002.0     10   2.500000        80.0
2  03-07-2019      1003.0     10   3.000000        60.0
3  06-07-2019      1004.0     11   0.000000        65.0
4  07-07-2019      1005.0     11   4.000000        70.0
5  08-07-2019      1006.0     11  10.000000        75.0
6  09-07-2019      1007.0     12   4.000000        80.0
7  10-07-2019      1008.0     12   4.666667        90.0
8  11-07-2019      1009.0     12   5.333333        60.0
9  12-07-2019      1010.0     12   6.000000        85.0

It is by default linear

In [13]:
df.interpolate(method="linear")

C:\Users\shwet\AppData\Local\Temp\ipykernel_28348\813095686.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method="linear")

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2019      1001.0     10   2.000000        50.0
1  02-07-2019      1002.0     10   2.500000        80.0
2  03-07-2019      1003.0     10   3.000000        60.0
3  06-07-2019      1004.0     11   0.000000        65.0
4  07-07-2019      1005.0     11   4.000000        70.0
5  08-07-2019      1006.0     11  10.000000        75.0
6  09-07-2019      1007.0     12   4.000000        80.0
7  10-07-2019      1008.0     12   4.666667        90.0
8  11-07-2019      1009.0     12   5.333333        60.0
9  12-07-2019      1010.0     12   6.000000        85.0

It will show error as time only works on DatetimeIndex

In [14]:
df.interpolate(method="time")

C:\Users\shwet\AppData\Local\Temp\ipykernel_28348\2048098757.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method="time")

ValueError: time-weighted interpolation only works on Series or DataFrames with a DatetimeIndex

In [ ]:
type(df.Date[0])

We can change datatype of date from string to Date

In [15]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Student_11.csv", parse_dates=["Date"])
df

        Date  Student ID  Class  Study hrs  Percentage
0 2019-01-07      1001.0     10        2.0        50.0
1 2019-02-07      1002.0     10        NaN        80.0
2 2019-03-07         NaN     10        3.0        60.0
3 2019-06-07         NaN     11        0.0         NaN
4 2019-07-07      1005.0     11        4.0         NaN
5 2019-08-07         NaN     11       10.0         NaN
6 2019-09-07      1007.0     12        4.0        80.0
7 2019-10-07      1008.0     12        NaN        90.0
8 2019-11-07      1009.0     12        NaN        60.0
9 2019-12-07      1010.0     12        6.0        85.0

In [16]:
type(df.Date[0])

pandas._libs.tslibs.timestamps.Timestamp

It is used to make Date column as index

In [17]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Student_11.csv", parse_dates=["Date"], index_col="Date")
df

            Student ID  Class  Study hrs  Percentage
Date
2019-01-07      1001.0     10        2.0        50.0
2019-02-07      1002.0     10        NaN        80.0
2019-03-07         NaN     10        3.0        60.0
2019-06-07         NaN     11        0.0         NaN
2019-07-07      1005.0     11        4.0         NaN
2019-08-07         NaN     11       10.0         NaN
2019-09-07      1007.0     12        4.0        80.0
2019-10-07      1008.0     12        NaN        90.0
2019-11-07      1009.0     12        NaN        60.0
2019-12-07      1010.0     12        6.0        85.0

It fills the missing values with nearest missing values eg in studentID and percentage unlike linear which fills next value

In [18]:
df.interpolate(method="time")

            Student ID  Class  Study hrs  Percentage
Date
2019-01-07     1001.00     10   2.000000   50.000000
2019-02-07     1002.00     10   2.525424   80.000000
2019-03-07     1002.56     10   3.000000   60.000000
2019-06-07     1004.40     11   0.000000   70.000000
2019-07-07     1005.00     11   4.000000   73.260870
2019-08-07     1006.00     11  10.000000   76.630435
2019-09-07     1007.00     12   4.000000   80.000000
2019-10-07     1008.00     12   4.659341   90.000000
2019-11-07     1009.00     12   5.340659   60.000000
2019-12-07     1010.00     12   6.000000   85.000000

There is error due to new update in python

In [19]:
df.interpolate(method="index")

            Student ID  Class  Study hrs  Percentage
Date
2019-01-07     1001.00     10   2.000000   50.000000
2019-02-07     1002.00     10   2.525424   80.000000
2019-03-07     1002.56     10   3.000000   60.000000
2019-06-07     1004.40     11   0.000000   70.000000
2019-07-07     1005.00     11   4.000000   73.260870
2019-08-07     1006.00     11  10.000000   76.630435
2019-09-07     1007.00     12   4.000000   80.000000
2019-10-07     1008.00     12   4.659341   90.000000
2019-11-07     1009.00     12   5.340659   60.000000
2019-12-07     1010.00     12   6.000000   85.000000

In [20]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Student_11.csv", parse_dates=["Date"], index_col="Class")
df

            Date  Student ID  Study hrs  Percentage
Class
10    2019-01-07      1001.0        2.0        50.0
10    2019-02-07      1002.0        NaN        80.0
10    2019-03-07         NaN        3.0        60.0
11    2019-06-07         NaN        0.0         NaN
11    2019-07-07      1005.0        4.0         NaN
11    2019-08-07         NaN       10.0         NaN
12    2019-09-07      1007.0        4.0        80.0
12    2019-10-07      1008.0        NaN        90.0
12    2019-11-07      1009.0        NaN        60.0
12    2019-12-07      1010.0        6.0        85.0

In studentID data is filled according to class as we have made it index

In [21]:
df.interpolate(method="index")

NotImplementedError:

It will take the nearest upper value

In [22]:
df.interpolate(method="nearest")

NotImplementedError:

In [23]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Student_11.csv", parse_dates=["Date"], index_col="Date")
df

            Student ID  Class  Study hrs  Percentage
Date
2019-01-07      1001.0     10        2.0        50.0
2019-02-07      1002.0     10        NaN        80.0
2019-03-07         NaN     10        3.0        60.0
2019-06-07         NaN     11        0.0         NaN
2019-07-07      1005.0     11        4.0         NaN
2019-08-07         NaN     11       10.0         NaN
2019-09-07      1007.0     12        4.0        80.0
2019-10-07      1008.0     12        NaN        90.0
2019-11-07      1009.0     12        NaN        60.0
2019-12-07      1010.0     12        6.0        85.0

In [24]:
df.interpolate(method = "polynomial", order=1)

ImportError: Missing optional dependency 'scipy'. polynomial interpolation requires SciPy. Use pip or conda to install scipy.

In [ ]:
df.interpolate(method = "spline", order=1)

In [25]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Student_11.csv")
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2019      1001.0     10        2.0        50.0
1  02-07-2019      1002.0     10        NaN        80.0
2  03-07-2019         NaN     10        3.0        60.0
3  06-07-2019         NaN     11        0.0         NaN
4  07-07-2019      1005.0     11        4.0         NaN
5  08-07-2019         NaN     11       10.0         NaN
6  09-07-2019      1007.0     12        4.0        80.0
7  10-07-2019      1008.0     12        NaN        90.0
8  11-07-2019      1009.0     12        NaN        60.0
9  12-07-2019      1010.0     12        6.0        85.0

In [26]:
df.interpolate()

C:\Users\shwet\AppData\Local\Temp\ipykernel_28348\4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2019      1001.0     10   2.000000        50.0
1  02-07-2019      1002.0     10   2.500000        80.0
2  03-07-2019      1003.0     10   3.000000        60.0
3  06-07-2019      1004.0     11   0.000000        65.0
4  07-07-2019      1005.0     11   4.000000        70.0
5  08-07-2019      1006.0     11  10.000000        75.0
6  09-07-2019      1007.0     12   4.000000        80.0
7  10-07-2019      1008.0     12   4.666667        90.0
8  11-07-2019      1009.0     12   5.333333        60.0
9  12-07-2019      1010.0     12   6.000000        85.0

In [27]:
df.dtypes

Date           object
Student ID    float64
Class           int64
Study hrs     float64
Percentage    float64
dtype: object

It will fill column according to the limit values provided, HEre 1 i provided so will fill 1 data in column

In [28]:
df.interpolate(limit=1)

C:\Users\shwet\AppData\Local\Temp\ipykernel_28348\1270544217.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(limit=1)

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2019      1001.0     10   2.000000        50.0
1  02-07-2019      1002.0     10   2.500000        80.0
2  03-07-2019      1003.0     10   3.000000        60.0
3  06-07-2019         NaN     11   0.000000        65.0
4  07-07-2019      1005.0     11   4.000000         NaN
5  08-07-2019      1006.0     11  10.000000         NaN
6  09-07-2019      1007.0     12   4.000000        80.0
7  10-07-2019      1008.0     12   4.666667        90.0
8  11-07-2019      1009.0     12        NaN        60.0
9  12-07-2019      1010.0     12   6.000000        85.0

In [29]:
df.interpolate(limit=2)

C:\Users\shwet\AppData\Local\Temp\ipykernel_28348\805236748.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(limit=2)

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2019      1001.0     10   2.000000        50.0
1  02-07-2019      1002.0     10   2.500000        80.0
2  03-07-2019      1003.0     10   3.000000        60.0
3  06-07-2019      1004.0     11   0.000000        65.0
4  07-07-2019      1005.0     11   4.000000        70.0
5  08-07-2019      1006.0     11  10.000000         NaN
6  09-07-2019      1007.0     12   4.000000        80.0
7  10-07-2019      1008.0     12   4.666667        90.0
8  11-07-2019      1009.0     12   5.333333        60.0
9  12-07-2019      1010.0     12   6.000000        85.0

Here backward values are filled with ref to data present below nd it is filled accoring to limits provided

In [31]:
df.interpolate(limit=1, limit_direction="backward")

C:\Users\shwet\AppData\Local\Temp\ipykernel_28348\1133712090.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(limit=1, limit_direction="backward")

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2019      1001.0     10   2.000000        50.0
1  02-07-2019      1002.0     10   2.500000        80.0
2  03-07-2019         NaN     10   3.000000        60.0
3  06-07-2019      1004.0     11   0.000000         NaN
4  07-07-2019      1005.0     11   4.000000         NaN
5  08-07-2019      1006.0     11  10.000000        75.0
6  09-07-2019      1007.0     12   4.000000        80.0
7  10-07-2019      1008.0     12        NaN        90.0
8  11-07-2019      1009.0     12   5.333333        60.0
9  12-07-2019      1010.0     12   6.000000        85.0

In [32]:
df.interpolate(limit=2, limit_direction="backward")

C:\Users\shwet\AppData\Local\Temp\ipykernel_28348\3298857590.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(limit=2, limit_direction="backward")

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2019      1001.0     10   2.000000        50.0
1  02-07-2019      1002.0     10   2.500000        80.0
2  03-07-2019      1003.0     10   3.000000        60.0
3  06-07-2019      1004.0     11   0.000000         NaN
4  07-07-2019      1005.0     11   4.000000        70.0
5  08-07-2019      1006.0     11  10.000000        75.0
6  09-07-2019      1007.0     12   4.000000        80.0
7  10-07-2019      1008.0     12   4.666667        90.0
8  11-07-2019      1009.0     12   5.333333        60.0
9  12-07-2019      1010.0     12   6.000000        85.0

If we use both it will fill both values 1 of forward and other of backward

In [33]:
df.interpolate(limit=1, limit_direction="both")

C:\Users\shwet\AppData\Local\Temp\ipykernel_28348\202217128.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(limit=1, limit_direction="both")

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2019      1001.0     10   2.000000        50.0
1  02-07-2019      1002.0     10   2.500000        80.0
2  03-07-2019      1003.0     10   3.000000        60.0
3  06-07-2019      1004.0     11   0.000000        65.0
4  07-07-2019      1005.0     11   4.000000         NaN
5  08-07-2019      1006.0     11  10.000000        75.0
6  09-07-2019      1007.0     12   4.000000        80.0
7  10-07-2019      1008.0     12   4.666667        90.0
8  11-07-2019      1009.0     12   5.333333        60.0
9  12-07-2019      1010.0     12   6.000000        85.0

Only fill NaNs surrounded by valid values

In [35]:
df.interpolate(limit_area="inside")

C:\Users\shwet\AppData\Local\Temp\ipykernel_28348\777483541.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(limit_area="inside")

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2019      1001.0     10   2.000000        50.0
1  02-07-2019      1002.0     10   2.500000        80.0
2  03-07-2019      1003.0     10   3.000000        60.0
3  06-07-2019      1004.0     11   0.000000        65.0
4  07-07-2019      1005.0     11   4.000000        70.0
5  08-07-2019      1006.0     11  10.000000        75.0
6  09-07-2019      1007.0     12   4.000000        80.0
7  10-07-2019      1008.0     12   4.666667        90.0
8  11-07-2019      1009.0     12   5.333333        60.0
9  12-07-2019      1010.0     12   6.000000        85.0

Only fill NaNs outside valid values (extrapolate)

In [37]:
df.interpolate(limit_area="outside")

C:\Users\shwet\AppData\Local\Temp\ipykernel_28348\1165182598.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(limit_area="outside")

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2019      1001.0     10        2.0        50.0
1  02-07-2019      1002.0     10        NaN        80.0
2  03-07-2019         NaN     10        3.0        60.0
3  06-07-2019         NaN     11        0.0         NaN
4  07-07-2019      1005.0     11        4.0         NaN
5  08-07-2019         NaN     11       10.0         NaN
6  09-07-2019      1007.0     12        4.0        80.0
7  10-07-2019      1008.0     12        NaN        90.0
8  11-07-2019      1009.0     12        NaN        60.0
9  12-07-2019      1010.0     12        6.0        85.0

In [38]:
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2019      1001.0     10        2.0        50.0
1  02-07-2019      1002.0     10        NaN        80.0
2  03-07-2019         NaN     10        3.0        60.0
3  06-07-2019         NaN     11        0.0         NaN
4  07-07-2019      1005.0     11        4.0         NaN
5  08-07-2019         NaN     11       10.0         NaN
6  09-07-2019      1007.0     12        4.0        80.0
7  10-07-2019      1008.0     12        NaN        90.0
8  11-07-2019      1009.0     12        NaN        60.0
9  12-07-2019      1010.0     12        6.0        85.0

It will update the original dataframe but we need to call seperately

In [40]:
df.interpolate(inplace=True)
df

C:\Users\shwet\AppData\Local\Temp\ipykernel_28348\28687744.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(inplace=True)

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2019      1001.0     10   2.000000        50.0
1  02-07-2019      1002.0     10   2.500000        80.0
2  03-07-2019      1003.0     10   3.000000        60.0
3  06-07-2019      1004.0     11   0.000000        65.0
4  07-07-2019      1005.0     11   4.000000        70.0
5  08-07-2019      1006.0     11  10.000000        75.0
6  09-07-2019      1007.0     12   4.000000        80.0
7  10-07-2019      1008.0     12   4.666667        90.0
8  11-07-2019      1009.0     12   5.333333        60.0
9  12-07-2019      1010.0     12   6.000000        85.0

Now since we used inplace so now our original dataframe is updated with new values

In [41]:
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2019      1001.0     10   2.000000        50.0
1  02-07-2019      1002.0     10   2.500000        80.0
2  03-07-2019      1003.0     10   3.000000        60.0
3  06-07-2019      1004.0     11   0.000000        65.0
4  07-07-2019      1005.0     11   4.000000        70.0
5  08-07-2019      1006.0     11  10.000000        75.0
6  09-07-2019      1007.0     12   4.000000        80.0
7  10-07-2019      1008.0     12   4.666667        90.0
8  11-07-2019      1009.0     12   5.333333        60.0
9  12-07-2019      1010.0     12   6.000000        85.0