Handling missing values in python

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv")
df

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN

will replace the value from not available to NaN

In [4]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv", na_values="not available")
df

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006.0,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010.0,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011.0,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,NaN,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024.0,NaN,NaN,NaN,NaN

In [5]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv", na_values={"Inception":"not available"})
df

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006.0,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010.0,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011.0,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,NaN,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024.0,NaN,NaN,NaN,NaN

Keeps default values from dataset like null, #N/A etc

In [6]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv", keep_default_na=False)
df

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",,11901180,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",#N/A,3138627,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN

In [7]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv", na_filter=False)
df

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",,11901180,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",#N/A,3138627,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN

In [8]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv")
df

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN

In [9]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv")
df.isnull()

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,True,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,True,False,False
11,False,True,True,True,False,True,True,True,True

Shows which column has null values

In [10]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv")
df.isnull().sum()

ID           0
Date         1
Name         1
Industry     1
Inception    0
Revenue      1
Expenses     3
Profit       1
Growth       1
dtype: int64

shows total null values of all columns

In [11]:
df.isnull().sum().sum()

9

In [12]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv")
df

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN

In [13]:
df.notnull()

      ID   Date   Name  Industry  Inception  Revenue  Expenses  Profit  Growth
0   True   True   True      True       True     True      True    True    True
1   True   True   True      True       True     True      True    True    True
2   True   True   True      True       True     True      True    True    True
3   True   True   True      True       True     True      True    True    True
4   True   True   True      True       True     True      True    True    True
5   True   True   True      True       True     True      True    True    True
6   True   True   True      True       True     True      True    True    True
7   True   True   True      True       True     True      True    True    True
8   True   True   True      True       True     True     False    True    True
9   True   True   True      True       True     True      True    True    True
10  True   True   True      True       True     True     False    True    True
11  True  False  False     False       True    False     False   False   False

In [14]:
df.notnull().sum()

ID           12
Date         11
Name         11
Industry     11
Inception    12
Revenue      11
Expenses      9
Profit       11
Growth       11
dtype: int64

In [15]:
df.notnull().sum().sum()

99

In [16]:
#Series
import numpy as np
sr=pd.Series([1,2,3,np.nan,4,np.NAN])
sr

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    NaN
dtype: float64

In [17]:
sr.isnull()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [18]:
sr.isnull().sum()

2

In [19]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv")
df

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN

Drops the rows which has missing values

In [20]:
df.dropna()

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%

Drops the column which has missing values....defauld axis value is zero so it drops row

In [21]:
df.dropna(axis=1)

    ID      Inception
0    1           2009
1    2           2010
2    3           2012
3    4           2013
4    5           2009
5    6           2006
6    7           2010
7    8           2009
8    9           2011
9   10           2011
10  11  not available
11  12           2024

drops rows and columns if they have NaN values

In [22]:
df.dropna(how = "any")

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%

only considers axis

In [23]:
df.dropna(axis=1, how="any")

    ID      Inception
0    1           2009
1    2           2010
2    3           2012
3    4           2013
4    5           2009
5    6           2006
6    7           2010
7    8           2009
8    9           2011
9   10           2011
10  11  not available
11  12           2024

Drops only when there are NaN values in all rows and columns

In [24]:
df.dropna(how = "all")

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN

Thresh is used when we need atleast one not null value in a row

In [25]:
df.dropna(thresh=1)

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN

if we set thresh=2 then it will select rows with atleast two not null values

In [26]:
df.dropna(thresh=2)

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN

In [27]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv")
df

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN

In [28]:
df.dropna(thresh=3)

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%

In [29]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv")
df

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN

It drops the entire row which has NaN values of the column we choose

In [30]:
df.dropna(subset="Expenses")

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [31]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv")
df

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,No,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180.0,18%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%
10,11,Yes,Techdrill,Health,not available,"$10,573,990",NaN,3138627.0,8%
11,12,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN

It drops the NaN value rows and doesnt creates new dataframe instead it updates the existing dataframe

In [32]:
df.dropna(inplace=True)

In [33]:
df

,ID,Date,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,No,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Yes,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Yes,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,No,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830.0,4%
9,10,Yes,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060.0,7%