Pandas Join method

DataFrame join is a convenient method for combining the columns of two potentially differently-indexed.

In [1]:
import pandas as pd

In [12]:
df1=pd.DataFrame({"A":[1,2,3],
                "B":[10,20,30]}
                )
df2=pd.DataFrame({"C":[4,5,6],
                "D":[40,50,60]})

display(df1,df2)

   A   B
0  1  10
1  2  20
2  3  30

   C   D
0  4  40
1  5  50
2  6  60

In [13]:
df1.join(df2)

   A   B  C   D
0  1  10  4  40
1  2  20  5  50
2  3  30  6  60

In [20]:
df1=pd.DataFrame({"A":[1,2,3],
                "B":[10,20,30]},
                 index=["a","b","c"]
                )
df2=pd.DataFrame({"C":[4,5,6],
                "D":[40,50,60]}
                )

display(df1,df2)

   A   B
a  1  10
b  2  20
c  3  30

   C   D
0  4  40
1  5  50
2  6  60

It is not considering df2 values as index is not similar/

In [21]:
df1.join(df2)

   A   B   C   D
a  1  10 NaN NaN
b  2  20 NaN NaN
c  3  30 NaN NaN

In [22]:
df1=pd.DataFrame({"A":[1,2,3],
                "B":[10,20,30]},
                 index=["a","b","c"]
                )
df2=pd.DataFrame({"C":[4,5,6],
                "D":[40,50,60]}
                )

display(df1,df2)

   A   B
a  1  10
b  2  20
c  3  30

   C   D
0  4  40
1  5  50
2  6  60

In [24]:
df1=pd.DataFrame({"A":[1,2,3],
                "B":[10,20,30]},
                 index=["a","b","c"]
                )
df2=pd.DataFrame({"C":[4,5],
                "D":[40,50]},
                index=["a","b"]
                )

display(df1,df2)

   A   B
a  1  10
b  2  20
c  3  30

   C   D
a  4  40
b  5  50

In [25]:
df1.join(df2)

   A   B    C     D
a  1  10  4.0  40.0
b  2  20  5.0  50.0
c  3  30  NaN   NaN

If there is missing data then we can use these parameters to get output accordingly

In [26]:
df1.join(df2,how="right")

   A   B  C   D
a  1  10  4  40
b  2  20  5  50

In [27]:
df1.join(df2,how="inner")

   A   B  C   D
a  1  10  4  40
b  2  20  5  50

In [28]:
df1.join(df2,how="outer")

   A   B    C     D
a  1  10  4.0  40.0
b  2  20  5.0  50.0
c  3  30  NaN   NaN

In [29]:
df1=pd.DataFrame({"A":[1,2,3],
                "B":[10,20,30]},
                 index=["a","b","c"]
                )
df2=pd.DataFrame({"A":[4,5],
                "D":[40,50]},
                index=["a","b"]
                )

display(df1,df2)

   A   B
a  1  10
b  2  20
c  3  30

   A   D
a  4  40
b  5  50

If we have two columns having same names and they are overlapping then we can use lsuffix and rsuffix to provide names

In [32]:
df1.join(df2, lsuffix="_1")

   A_1   B    A     D
a    1  10  4.0  40.0
b    2  20  5.0  50.0
c    3  30  NaN   NaN

In [33]:
df1.join(df2, rsuffix="_1")

   A   B  A_1     D
a  1  10  4.0  40.0
b  2  20  5.0  50.0
c  3  30  NaN   NaN