How to write csv files in pandas

In [1]:
import pandas as pd

In [6]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv")
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df.columns

Index(['ID', 'Name', 'Industry', 'Inception', 'Revenue', 'Expenses', 'Profit',
       'Growth'],
      dtype='object')

In [13]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv", nrows=4)
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%

In [23]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv", usecols=([2,4,7]))
df

              Industry       Revenue Growth
0          IT Services  $11,757,018     30%
1   Financial Services  $12,329,371     20%
2               Health  $10,597,009      7%
3          IT Services  $14,026,934     26%
4               Health  $10,573,990      8%
5               Health  $13,898,119     23%
6               Health   $9,254,614      6%
7               Health   $9,451,943      4%
8          IT Services  $14,001,180     18%
9  Government Services  $11,088,336      7%

In [18]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv", skiprows=[3])
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
3,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
4,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
5,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
6,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
7,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
8,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [29]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv", index_col = "Name")
df

,ID,Industry,Inception,Revenue,Expenses,Profit,Growth
Name,,,,,,,
Lamtone,1,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
Stripfind,2,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
Canecorporation,3,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
Mattouch,4,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
Techdrill,5,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
Techline,6,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
Cityace,7,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
Kayelectronics,8,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
Ganzlax,9,IT Services,2011,"$14,001,180",NaN,11901180,18%
Trantraxlax,10,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [32]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv", index_col = 5)
df

,ID,Name,Industry,Inception,Revenue,Profit,Growth
Expenses,,,,,,,
"6,482,465 Dollars",1,Lamtone,IT Services,2009,"$11,757,018",5274553,30%
"916,455 Dollars",2,Stripfind,Financial Services,2010,"$12,329,371",11412916,20%
"7,591,189 Dollars",3,Canecorporation,Health,2012,"$10,597,009",3005820,7%
"7,429,377 Dollars",4,Mattouch,IT Services,2013,"$14,026,934",6597557,26%
"7,435,363 Dollars",5,Techdrill,Health,2009,"$10,573,990",3138627,8%
"5,470,303 Dollars",6,Techline,Health,2006,"$13,898,119",8427816,23%
"6,249,498 Dollars",7,Cityace,Health,2010,"$9,254,614",3005116,6%
"3,878,113 Dollars",8,Kayelectronics,Health,2009,"$9,451,943",5573830,4%
NaN,9,Ganzlax,IT Services,2011,"$14,001,180",11901180,18%
"5,635,276 Dollars",10,Trantraxlax,Government Services,2011,"$11,088,336",5453060,7%

In [33]:
df.head(3)

,ID,Name,Industry,Inception,Revenue,Profit,Growth
Expenses,,,,,,,
"6,482,465 Dollars",1,Lamtone,IT Services,2009,"$11,757,018",5274553,30%
"916,455 Dollars",2,Stripfind,Financial Services,2010,"$12,329,371",11412916,20%
"7,591,189 Dollars",3,Canecorporation,Health,2012,"$10,597,009",3005820,7%

In [34]:
df=pd.read_csv("D:\Programming\Python programming\Pandas\Fortune_10.csv")
df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [35]:
df.head(5)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%

In [36]:
df.tail(5)

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         10 non-null     int64
 1   Name       10 non-null     object
 2   Industry   10 non-null     object
 3   Inception  10 non-null     int64
 4   Revenue    10 non-null     object
 5   Expenses   9 non-null      object
 6   Profit     10 non-null     int64
 7   Growth     10 non-null     object
dtypes: int64(3), object(5)
memory usage: 772.0+ bytes